version: "3.8"

services:
  bilingual_book_maker:
    build: .
    container_name: bilingual_book_maker
    volumes:
      - ${folder_path}:/app/test_books
    environment:
      folder_path: ${folder_path}
      book_name: ${book_name}
      openai_key: ${openai_key}
      language: ${language}
      azure_api_base: ${azure_api_base}
      azure_deployment_id: ${azure_deployment_id}
    command:
      [
        "--book_name",
        "${book_name}",
        "--openai_key",
        "${openai_key}",
        "--test",
        "--language",
        "${language}",
        "--api_base",
        "${azure_api_base}",
        "--deployment_id",
        "${azure_deployment_id}",
      ]
